create table if not exists public.ai_provider_catalog (
  provider_key text primary key,
  display_name text not null,
  adapter_kind text not null check (adapter_kind in ('openai_compatible')),
  base_url text not null,
  credential_env text,
  is_local boolean not null default false,
  enabled boolean not null default false,
  capabilities text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_model_catalog (
  id uuid primary key default gen_random_uuid(),
  provider_key text not null references public.ai_provider_catalog(provider_key) on update cascade on delete restrict,
  model_key text not null,
  display_name text not null,
  capabilities text[] not null default '{}',
  context_window_tokens integer check (context_window_tokens is null or context_window_tokens > 0),
  max_output_tokens integer check (max_output_tokens is null or max_output_tokens > 0),
  input_cost_microusd_per_million bigint not null default 0 check (input_cost_microusd_per_million >= 0),
  output_cost_microusd_per_million bigint not null default 0 check (output_cost_microusd_per_million >= 0),
  enabled boolean not null default false,
  priority integer not null default 100,
  resource_profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider_key, model_key)
);

create table if not exists public.ai_workspace_policies (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  capability text not null,
  preferred_model_id uuid references public.ai_model_catalog(id) on delete set null,
  fallback_model_ids uuid[] not null default '{}',
  max_cost_microusd bigint check (max_cost_microusd is null or max_cost_microusd >= 0),
  max_latency_ms integer check (max_latency_ms is null or max_latency_ms > 0),
  require_local boolean not null default false,
  enabled boolean not null default true,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, capability)
);

create table if not exists public.ai_request_runs (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  module text not null,
  action text not null,
  capability text not null,
  sensitivity text not null default 'internal'
    check (sensitivity in ('public','internal','confidential','restricted')),
  provider_key text,
  model_key text,
  status text not null default 'queued'
    check (status in ('queued','running','succeeded','failed','blocked')),
  input_digest text,
  output_digest text,
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  total_tokens integer not null default 0 check (total_tokens >= 0),
  cost_microusd bigint not null default 0 check (cost_microusd >= 0),
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  error_code text,
  error_message text,
  correlation_id uuid not null default gen_random_uuid(),
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.company_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  domain text not null,
  event_type text not null,
  entity_type text,
  entity_id text,
  correlation_id uuid,
  idempotency_key text,
  payload jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists company_events_workspace_idempotency_uq
  on public.company_events(workspace_id, idempotency_key)
  where idempotency_key is not null;

create table if not exists public.company_memory_entries (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  source_event_id bigint references public.company_events(id) on delete set null,
  domain text not null,
  memory_type text not null,
  subject_type text,
  subject_id text,
  title text not null,
  summary text not null,
  structured_data jsonb not null default '{}'::jsonb,
  sensitivity text not null default 'internal'
    check (sensitivity in ('public','internal','confidential','restricted')),
  status text not null default 'active'
    check (status in ('active','superseded','archived')),
  content_hash text not null,
  occurred_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists company_memory_workspace_hash_uq
  on public.company_memory_entries(workspace_id, content_hash);

create index if not exists ai_model_catalog_capabilities_idx on public.ai_model_catalog using gin(capabilities);
create index if not exists ai_workspace_policies_workspace_idx on public.ai_workspace_policies(workspace_id, capability);
create index if not exists ai_request_runs_workspace_created_idx on public.ai_request_runs(workspace_id, created_at desc);
create index if not exists ai_request_runs_correlation_idx on public.ai_request_runs(correlation_id);
create index if not exists company_events_workspace_occurred_idx on public.company_events(workspace_id, occurred_at desc);
create index if not exists company_events_entity_idx on public.company_events(workspace_id, entity_type, entity_id);
create index if not exists company_memory_workspace_domain_idx on public.company_memory_entries(workspace_id, domain, created_at desc);
create index if not exists company_memory_subject_idx on public.company_memory_entries(workspace_id, subject_type, subject_id);

drop trigger if exists set_ai_provider_catalog_updated_at on public.ai_provider_catalog;
create trigger set_ai_provider_catalog_updated_at before update on public.ai_provider_catalog
for each row execute function private.set_updated_at();
drop trigger if exists set_ai_model_catalog_updated_at on public.ai_model_catalog;
create trigger set_ai_model_catalog_updated_at before update on public.ai_model_catalog
for each row execute function private.set_updated_at();
drop trigger if exists set_ai_workspace_policies_updated_at on public.ai_workspace_policies;
create trigger set_ai_workspace_policies_updated_at before update on public.ai_workspace_policies
for each row execute function private.set_updated_at();
drop trigger if exists set_company_memory_entries_updated_at on public.company_memory_entries;
create trigger set_company_memory_entries_updated_at before update on public.company_memory_entries
for each row execute function private.set_updated_at();

alter table public.ai_provider_catalog enable row level security;
alter table public.ai_model_catalog enable row level security;
alter table public.ai_workspace_policies enable row level security;
alter table public.ai_request_runs enable row level security;
alter table public.company_events enable row level security;
alter table public.company_memory_entries enable row level security;

revoke all on public.ai_provider_catalog from anon, authenticated;
revoke all on public.ai_model_catalog from anon, authenticated;
revoke all on public.ai_workspace_policies from anon, authenticated;
revoke all on public.ai_request_runs from anon, authenticated;
revoke all on public.company_events from anon, authenticated;
revoke all on public.company_memory_entries from anon, authenticated;

grant select, insert, update, delete on public.ai_workspace_policies to authenticated;
grant select on public.ai_request_runs to authenticated;
grant select on public.company_events to authenticated;
grant select on public.company_memory_entries to authenticated;

create policy ai_workspace_policies_select_member on public.ai_workspace_policies for select to authenticated
using ((select private.is_workspace_member(ai_workspace_policies.workspace_id)));
create policy ai_workspace_policies_insert_admin on public.ai_workspace_policies for insert to authenticated
with check ((select private.is_workspace_admin(ai_workspace_policies.workspace_id)) and (select private.orbit_workspace_can_write(ai_workspace_policies.workspace_id)));
create policy ai_workspace_policies_update_admin on public.ai_workspace_policies for update to authenticated
using ((select private.is_workspace_admin(ai_workspace_policies.workspace_id)) and (select private.orbit_workspace_can_write(ai_workspace_policies.workspace_id)))
with check ((select private.is_workspace_admin(ai_workspace_policies.workspace_id)) and (select private.orbit_workspace_can_write(ai_workspace_policies.workspace_id)));
create policy ai_workspace_policies_delete_admin on public.ai_workspace_policies for delete to authenticated
using ((select private.is_workspace_admin(ai_workspace_policies.workspace_id)) and (select private.orbit_workspace_can_write(ai_workspace_policies.workspace_id)));

create policy ai_request_runs_select_member on public.ai_request_runs for select to authenticated
using ((select private.is_workspace_member(ai_request_runs.workspace_id)));
create policy company_events_select_member on public.company_events for select to authenticated
using ((select private.is_workspace_member(company_events.workspace_id)));
create policy company_memory_entries_select_admin on public.company_memory_entries for select to authenticated
using ((select private.is_workspace_admin(company_memory_entries.workspace_id)));

insert into public.ai_provider_catalog (
  provider_key, display_name, adapter_kind, base_url, credential_env, is_local, enabled, capabilities, metadata
) values
  ('openai', 'OpenAI', 'openai_compatible', 'https://api.openai.com', 'OPENAI_API_KEY', false, false, array['chat'], '{"seeded_by":"stage1_sovereign_ai_foundation"}'::jsonb),
  ('urava_local', 'Urava Local', 'openai_compatible', 'http://127.0.0.1:8000', null, true, false, array['chat'], '{"seeded_by":"stage1_sovereign_ai_foundation"}'::jsonb)
on conflict (provider_key) do nothing;
